import type { Incident } from "./types";

export const expiredInternalMtlsCert = {
  slug: "expired-internal-mtls-cert",
  title:
    "No deploy, no traffic change — every internal call fails at exactly 00:00:07",
  publishedAt: "2026-10-04",
  difficulty: "easy",
  topic: "platform",
  tags: ["tls", "mtls", "certificates", "expiry", "observability"],
  symptom:
    "Your product runs 38 services behind a public ingress. At 00:00:07 UTC, customers start seeing 502s on nearly every page. Nothing was deployed today, traffic is a normal late-night trickle, and CPU, memory, and database dashboards are all green. The on-call engineer rolls back yesterday's release and restarts the busiest services. Neither changes anything.",
  constraints: [
    "Services talk to each other over mTLS, and each service mounts the same certificate and key from a shared secret",
    "The public ingress certificate is issued and renewed automatically",
    "Staging runs the same code and the same architecture",
    "Your only expiry monitoring is a dashboard panel for the ingress certificates",
    "The engineer who set up the internal CA has since left the company",
  ],
  evidence: [
    "All 38 services start failing in the same second, 00:00:07, with no deploy and no traffic change",
    "Every internal error line reads x509: certificate has expired or is not yet valid, and the current time in it is 00:00:09, two seconds past the certificate's end date",
    "The ingress certificate, which renews automatically, has 61 days left and is healthy",
    "The internal certificate has Not Before: 2025-10-04 and Not After: 2026-10-04 — exactly one year, generated by a one-off command",
    "Staging is healthy. Its certificate was generated in March",
    "Restarting any pod changes nothing, and the pod mounts the same secret",
  ],
  question:
    "Why did everything fail at once, why did a rollback and restarts not help, and what would you change so it can't happen again?",
  picks: [
    {
      id: "most-likely-cause",
      prompt: "What's the most likely cause?",
      options: [
        { id: "mesh-config", label: "A bad service-mesh config rollout" },
        { id: "dns-outage", label: "A DNS outage" },
        {
          id: "shared-cert-expired",
          label:
            "A shared internal certificate with a fixed one-year lifetime expired, so every mTLS handshake failed at once",
        },
        { id: "clock-drift", label: "Clock drift on a single node" },
      ],
      answer: "shared-cert-expired",
    },
    {
      id: "why-rollback-failed",
      prompt: "Why didn't rollbacks and restarts help?",
      options: [
        { id: "too-slow", label: "Restarts were too slow to take effect" },
        {
          id: "code-not-cert",
          label:
            "The rollback and restarts changed the code, not the certificate, and every pod mounts the same expired secret",
        },
        { id: "wrong-order", label: "The pods were restarted in the wrong order" },
        { id: "lb-cached", label: "The load balancer cached the failure" },
      ],
      answer: "code-not-cert",
    },
    {
      id: "long-term-fix",
      prompt: "What is the best long-term fix?",
      options: [
        {
          id: "longer-lifetime",
          label: "Reissue the certificate with a 10-year lifetime",
        },
        {
          id: "calendar-reminder",
          label: "Add a calendar reminder for next October",
        },
        {
          id: "skip-verification",
          label: "Skip certificate verification between internal services",
        },
        {
          id: "automate-rotation",
          label:
            "Automate issuance and rotation of short-lived certificates (cert-manager or the mesh CA), and alert on days-to-expiry for every certificate",
        },
      ],
      answer: "automate-rotation",
    },
  ],
  diagnosis: `The failure is a single date baked into a single artifact. One certificate with a fixed lifetime was shared by every service, so all 38 broke in the same second — a fleet-wide rollout of a broken shared secret, minus the rollout.

Code changes can't fix it. The expired certificate is identical on every pod, so shipping older code changes nothing, and restarting a pod remounts the same secret. That is why the rollback and the restarts were both no-ops: they renewed the processes and the code, never the thing that was actually failing — the handshake itself, which every client rejects before any request handling begins.

Nothing announced it because the expiry lived outside the monitoring. The dashboard covered the ingress certificate, which had been renewed automatically and sat 61 days out. The internal CA was a one-off command run by an engineer who has since left; the certificate it made was in no inventory, so no alert knew it existed, let alone that it was running out.`,
  fix: `During the incident, the fastest safe mitigation: issue a fresh certificate from the internal CA, update the shared secret, and reload services in a rolling fashion. Clients and servers swap to a valid cert without a big-bang restart, and verification stays on the whole time.

Long-term, the choice is a tradeoff:

| Option | Tradeoff |
| --- | --- |
| Short-lived, auto-rotated certs | More moving parts, and a failed renewal becomes the next incident — so renew at about two-thirds of the lifetime and alert on failed renewals |
| Longer lifetime (10 years) | Delays the same outage until nobody remembers how the cert was made, and widens the window if the key leaks |
| Disable verification during the outage | Fastest, but removes service authentication and tends to stay in place after the incident |
| Inventory plus days-to-expiry alerts on every certificate | Cheap and high value, but only warns you — it does not replace rotation |

Automate issuance and rotation of short-lived certificates (cert-manager or the mesh CA), keep a full inventory, and alert on days-to-expiry for every certificate, with a critical page inside one week.`,
  rubric: [
    {
      text: "Read the shared-secret constraint and the single Not After date as the trigger, not the 502s themselves",
      dim: "correctness",
    },
    {
      text: "Explained that rollback and restarts cannot help because they change code/processes, not the mounted certificate",
      dim: "process",
    },
    {
      text: "Went past the cert itself to the monitoring gap: an expiry nobody owned and nothing tracked",
      dim: "depth",
    },
  ],
  remember: [
    "Every certificate expires on a wall-clock date you did not choose — if it is not in an inventory with a days-to-expiry alert, someone will meet that date first.",
    "Restarts and rollbacks renew code and processes. Anything that fails at the handshake layer — a shared cert, a clock skew — survives both.",
    "Automate rotation or accept a yearly outage: a certificate renewed by a one-off command is a calendar invite, not a control plane.",
  ],
} satisfies Incident;
